language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jemlifathi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jemlifathi/react-test npm run test -- --coverage

after_success:
  - docker build -t jemlifathi/multi-client ./client
  - docker build -t jemlifathi/multi-nginx ./nginx
  - docker build -t jemlifathi/multi-server ./server
  - docker build -t jemlifathi/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jemlifathi/multi-client
  - docker push jemlifathi/multi-nginx
  - docker push jemlifathi/multi-server
  - docker push jemlifathi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-376562838138"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY